name: Deploy emails
on:
  repository_dispatch:
    types: rebuild
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Node packages
      run: npm install

    - name: Build assets
      run: npm run-script build

    - name: Deploy assets
      run: npm run-script deploy
      env:
        JUSTLIBERALS_ORG_UK_EMAIL_BUCKET: ${{ secrets.JUSTLIBERALS_ORG_UK_EMAIL_S3_BUCKET_NAME }}
        JUSTLIBERALS_ORG_UK_WEBSITE_BUCKET: ${{ secrets.JUSTLIBERALS_ORG_UK_WEBSITE_S3_BUCKET_NAME }}
        JUSTLIBERALS_ORG_UK_DISTRIBUTION: ${{ secrets.JUSTLIBERALS_ORG_UK_CLOUDFRONT_DISTRIBUTION }}
        ALDES_ORG_UK_WEBSITE_BUCKET: ${{ secrets.ALDES_ORG_UK_WEBSITE_S3_BUCKET_NAME }}
        ALDES_ORG_UK_DISTRIBUTION: ${{ secrets.ALDES_ORG_UK_CLOUDFRONT_DISTRIBUTION }}